### PR TITLE
fix: replaced deprecated enum (#173)

### PR DESCRIPTION
**Pull request by inc-ali**
See #173

### CODE REVIEW

**Comment by luck3rhoch3** [comment]
I have installed 0.5.0.

Still have the warning:
2024-01-09 20:21:32.987 WARNING (MainThread) [homeassistant.components.lock] SUPPORT_OPEN was used from nuki_ng, this is a deprecated constant which will be removed in HA Core 2025.1. Use LockEntityFeature.OPEN instead, please create a bug report at https://github.com/kvj/hass_nuki_ng/issues

**Comment by luck3rhoch3** [comment]
Screenshot_20240109_203632_Chrome

**Comment by inc-ali** [comment]
@kvj anything I should improve?

**Comment by kvj** [comment]
Thanks for the contribution! Looks good, merging now

**Pull request merged**
