### PR TITLE
[Opener] Improvements for continuous mode

### PR DESCRIPTION
**Pull request by alucar-d**
- Actually when continuous mode is activated, the opener "lock" control and "locked" sensor shows as "locked". This PR check also continuous mode to determine the lock state
- Add configuration switch in opener to activate/deactivate continuous mode

### CODE REVIEW

**Comment by kvj** [comment]
Hey @alucar-d looks like a nice improvement, but I can't find any API documentation for `activate_continuous_mode` / `deactivate_continuous_mode` actions. Could you please add a reference to it?

**Comment by alucar-d** [comment]
Hi @kvj, the documentation for these actions at Nuki API level is in the ["lock actions" section](https://developer.nuki.io/page/nuki-bridge-http-api-1-13/4/#heading--lock-actions). The last two rows on the "opener" column.
These actions are actually mapped in the code for both "[bridge_lock_actions](https://github.com/kvj/hass_nuki_ng/blob/main/custom_components/nuki_ng/nuki.py#L97)" and "[web_lock_actions](https://github.com/kvj/hass_nuki_ng/blob/main/custom_components/nuki_ng/nuki.py#L124)". I just made use of it :)
Thanks for your time!

**Comment by sebastianandress** [comment]
For those who don't want to wait for this merge, you can also get the current mode of your Nuki Opener using the rest platform:

```
sensor:
  - platform: rest
    unique_id: sensor.nuki_mode
    resource: http://[BRIDGE_IP_ADDRESS]:8080/list
    params:
      token: !secret nuki_token
    scan_interval: 20
    name: Nuki Mode
    value_template: "{{ value_json[0].lastKnownState.mode }}"
```

If the sensor returns a value of 2, continuous mode is inactive, if it is 3 continuous mode is active.
However I'm looking forward to see this built in once this branch is merged!

**Comment by GNeras** [comment]
I think this is a good idea. The only issue I have with this is that when continuous mode is enabled, if I try to lock the Opener, it does nothing because the lock action doesn't change the continuous mode. Maybe locking should also disable continuous mode.

**Comment by alucar-d** [comment]
> I think this is a good idea. The only issue I have with this is that when continuous mode is enabled, if I try to lock the Opener, it does nothing because the lock action doesn't change the continuous mode. Maybe locking should also disable continuous mode.

It's a good point!
I think that the behavior should be as you said, so I'll try to adjust it.
Thanks for your comment

**Comment by alucar-d** [comment]
Updated the behavior. Now when lock an opener it checks if continuos mode is enabled and made an extra call to disable continuos mode before call the lock itself.

**Comment by GNeras** [comment]
I tested it and I think it's perfect now :+1:

**Comment by alucar-d** [comment]
resolve #161

**Comment by tristanXme** [comment]
Tested it and its also working for me. Please merge it.

**Pull request merged**
